create database company01;

use company01;
create table employees(
ID INT primary key auto_increment,
name varchar(100),
position varchar(100),
salary decimal(10,2),
date_of_joining date 
);
INSERT INTO EMPLOYEES VALUES(
1,"JOHN DOE", "MANAGER", 55000.00,"2020-01-15");
INSERT INTO EMPLOYEES VALUES(
2,"JANE SMITH", "DEVELOPER", 48000.00,"2019-07-10");
INSERT INTO EMPLOYEES VALUES(
3,"ALICE JOHNSON", "DESIGNER", 45000.00,"2021-03-22");

INSERT INTO EMPLOYEES VALUES(
4,"BOB BROWN", "DEVELOPER", 50000.00,"2018-11-01");
SELECT * FROM EMPLOYEES
WHERE POSITION ="DEVELOPER";
UPDATE EMPLOYEES
SET SALARY =46000.00
WHERE NAME="ALICE JOHNSON";
SET SQL_SAFE_UPDATES=0;
DELETE FROM EMPLOYEES
WHERE NAME="BOB BROWN";

SELECT * FROM EMPLOYEES
WHERE SALARY >48000;
alter table employees 
add email varchar(50);
update employees
set email="john.doe@company.com"
where name='JOHN DOE';
SELECT NAME, SALARY FROM EMPLOYEES;

SELECT COUNT(*)FROM EMPLOYEES
WHERE Date_of_Joining >"2020-01-01";

SELECT* FROM EMPLOYEES
ORDER BY SALARY DESC;

ALTER TABLE EMPLOYEES
DROP EMAIL;
SELECT* FROM EMPLOYEES;

SELECT MAX(SALARY) FROM EMPLOYEES;

